spring:
  datasource:
    url: jdbc:postgresql://postgres.cpgjw7gricns.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: elephant
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

  metrics:
    distribution:
     percentiles-histogram.http.server.requests: true
     percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999